export default {

  CURRENT_USER_RECEIVED: 'CURRENT_USER_RECEIVED',
  USER_LOGGED_OUT: 'USER_LOGGED_OUT',

  CURRENT_LOCATION_CHANGED: 'CURRENT_LOCATION_CHANGED',
  POSTS_RECEIVED: 'POSTS_RECEIVED',

}